import { ALL_FANZ } from './fanz';

export const FLAG_AVATARS = [
  { id: 'flag-af', url: 'https://flagcdn.com/w160/af.png', label: 'Afghanistan' },
  { id: 'flag-za', url: 'https://flagcdn.com/w160/za.png', label: 'Afrique du Sud' },
  { id: 'flag-al', url: 'https://flagcdn.com/w160/al.png', label: 'Albanie' },
  { id: 'flag-dz', url: 'https://flagcdn.com/w160/dz.png', label: 'Algérie' },
  { id: 'flag-de', url: 'https://flagcdn.com/w160/de.png', label: 'Allemagne' },
  { id: 'flag-ad', url: 'https://flagcdn.com/w160/ad.png', label: 'Andorre' },
  { id: 'flag-ao', url: 'https://flagcdn.com/w160/ao.png', label: 'Angola' },
  { id: 'flag-ag', url: 'https://flagcdn.com/w160/ag.png', label: 'Antigua-et-Barbuda' },
  { id: 'flag-sa', url: 'https://flagcdn.com/w160/sa.png', label: 'Arabie Saoudite' },
  { id: 'flag-ar', url: 'https://flagcdn.com/w160/ar.png', label: 'Argentine' },
  { id: 'flag-am', url: 'https://flagcdn.com/w160/am.png', label: 'Arménie' },
  { id: 'flag-au', url: 'https://flagcdn.com/w160/au.png', label: 'Australie' },
  { id: 'flag-at', url: 'https://flagcdn.com/w160/at.png', label: 'Autriche' },
  { id: 'flag-az', url: 'https://flagcdn.com/w160/az.png', label: 'Azerbaïdjan' },
  { id: 'flag-bs', url: 'https://flagcdn.com/w160/bs.png', label: 'Bahamas' },
  { id: 'flag-bh', url: 'https://flagcdn.com/w160/bh.png', label: 'Bahreïn' },
  { id: 'flag-bd', url: 'https://flagcdn.com/w160/bd.png', label: 'Bangladesh' },
  { id: 'flag-bb', url: 'https://flagcdn.com/w160/bb.png', label: 'Barbade' },
  { id: 'flag-be', url: 'https://flagcdn.com/w160/be.png', label: 'Belgique' },
  { id: 'flag-bz', url: 'https://flagcdn.com/w160/bz.png', label: 'Belize' },
  { id: 'flag-bj', url: 'https://flagcdn.com/w160/bj.png', label: 'Bénin' },
  { id: 'flag-bt', url: 'https://flagcdn.com/w160/bt.png', label: 'Bhoutan' },
  { id: 'flag-by', url: 'https://flagcdn.com/w160/by.png', label: 'Biélorussie' },
  { id: 'flag-mm', url: 'https://flagcdn.com/w160/mm.png', label: 'Birmanie' },
  { id: 'flag-bo', url: 'https://flagcdn.com/w160/bo.png', label: 'Bolivie' },
  { id: 'flag-ba', url: 'https://flagcdn.com/w160/ba.png', label: 'Bosnie-Herzégovine' },
  { id: 'flag-bw', url: 'https://flagcdn.com/w160/bw.png', label: 'Botswana' },
  { id: 'flag-br', url: 'https://flagcdn.com/w160/br.png', label: 'Brésil' },
  { id: 'flag-bn', url: 'https://flagcdn.com/w160/bn.png', label: 'Brunei' },
  { id: 'flag-bg', url: 'https://flagcdn.com/w160/bg.png', label: 'Bulgarie' },
  { id: 'flag-bf', url: 'https://flagcdn.com/w160/bf.png', label: 'Burkina Faso' },
  { id: 'flag-bi', url: 'https://flagcdn.com/w160/bi.png', label: 'Burundi' },
  { id: 'flag-kh', url: 'https://flagcdn.com/w160/kh.png', label: 'Cambodge' },
  { id: 'flag-cm', url: 'https://flagcdn.com/w160/cm.png', label: 'Cameroun' },
  { id: 'flag-ca', url: 'https://flagcdn.com/w160/ca.png', label: 'Canada' },
  { id: 'flag-cv', url: 'https://flagcdn.com/w160/cv.png', label: 'Cap-Vert' },
  { id: 'flag-cl', url: 'https://flagcdn.com/w160/cl.png', label: 'Chili' },
  { id: 'flag-cn', url: 'https://flagcdn.com/w160/cn.png', label: 'Chine' },
  { id: 'flag-cy', url: 'https://flagcdn.com/w160/cy.png', label: 'Chypre' },
  { id: 'flag-co', url: 'https://flagcdn.com/w160/co.png', label: 'Colombie' },
  { id: 'flag-km', url: 'https://flagcdn.com/w160/km.png', label: 'Comores' },
  { id: 'flag-cg', url: 'https://flagcdn.com/w160/cg.png', label: 'Congo' },
  { id: 'flag-kp', url: 'https://flagcdn.com/w160/kp.png', label: 'Corée du Nord' },
  { id: 'flag-kr', url: 'https://flagcdn.com/w160/kr.png', label: 'Corée du Sud' },
  { id: 'flag-cr', url: 'https://flagcdn.com/w160/cr.png', label: 'Costa Rica' },
  { id: 'flag-ci', url: 'https://flagcdn.com/w160/ci.png', label: "Côte d'Ivoire" },
  { id: 'flag-hr', url: 'https://flagcdn.com/w160/hr.png', label: 'Croatie' },
  { id: 'flag-cu', url: 'https://flagcdn.com/w160/cu.png', label: 'Cuba' },
  { id: 'flag-dk', url: 'https://flagcdn.com/w160/dk.png', label: 'Danemark' },
  { id: 'flag-dj', url: 'https://flagcdn.com/w160/dj.png', label: 'Djibouti' },
  { id: 'flag-dm', url: 'https://flagcdn.com/w160/dm.png', label: 'Dominique' },
  { id: 'flag-eg', url: 'https://flagcdn.com/w160/eg.png', label: 'Égypte' },
  { id: 'flag-ae', url: 'https://flagcdn.com/w160/ae.png', label: 'Émirats arabes unis' },
  { id: 'flag-ec', url: 'https://flagcdn.com/w160/ec.png', label: 'Équateur' },
  { id: 'flag-er', url: 'https://flagcdn.com/w160/er.png', label: 'Érythrée' },
  { id: 'flag-es', url: 'https://flagcdn.com/w160/es.png', label: 'Espagne' },
  { id: 'flag-ee', url: 'https://flagcdn.com/w160/ee.png', label: 'Estonie' },
  { id: 'flag-sz', url: 'https://flagcdn.com/w160/sz.png', label: 'Eswatini' },
  { id: 'flag-us', url: 'https://flagcdn.com/w160/us.png', label: 'États-Unis' },
  { id: 'flag-et', url: 'https://flagcdn.com/w160/et.png', label: 'Éthiopie' },
  { id: 'flag-fj', url: 'https://flagcdn.com/w160/fj.png', label: 'Fidji' },
  { id: 'flag-fi', url: 'https://flagcdn.com/w160/fi.png', label: 'Finlande' },
  { id: 'flag-fr', url: 'https://flagcdn.com/w160/fr.png', label: 'France' },
  { id: 'flag-ga', url: 'https://flagcdn.com/w160/ga.png', label: 'Gabon' },
  { id: 'flag-gm', url: 'https://flagcdn.com/w160/gm.png', label: 'Gambie' },
  { id: 'flag-ge', url: 'https://flagcdn.com/w160/ge.png', label: 'Géorgie' },
  { id: 'flag-gh', url: 'https://flagcdn.com/w160/gh.png', label: 'Ghana' },
  { id: 'flag-gr', url: 'https://flagcdn.com/w160/gr.png', label: 'Grèce' },
  { id: 'flag-gd', url: 'https://flagcdn.com/w160/gd.png', label: 'Grenade' },
  { id: 'flag-gt', url: 'https://flagcdn.com/w160/gt.png', label: 'Guatemala' },
  { id: 'flag-gn', url: 'https://flagcdn.com/w160/gn.png', label: 'Guinée' },
  { id: 'flag-gq', url: 'https://flagcdn.com/w160/gq.png', label: 'Guinée équatoriale' },
  { id: 'flag-gw', url: 'https://flagcdn.com/w160/gw.png', label: 'Guinée-Bissau' },
  { id: 'flag-gy', url: 'https://flagcdn.com/w160/gy.png', label: 'Guyana' },
  { id: 'flag-ht', url: 'https://flagcdn.com/w160/ht.png', label: 'Haïti' },
  { id: 'flag-hn', url: 'https://flagcdn.com/w160/hn.png', label: 'Honduras' },
  { id: 'flag-hu', url: 'https://flagcdn.com/w160/hu.png', label: 'Hongrie' },
  { id: 'flag-in', url: 'https://flagcdn.com/w160/in.png', label: 'Inde' },
  { id: 'flag-id', url: 'https://flagcdn.com/w160/id.png', label: 'Indonésie' },
  { id: 'flag-iq', url: 'https://flagcdn.com/w160/iq.png', label: 'Irak' },
  { id: 'flag-ir', url: 'https://flagcdn.com/w160/ir.png', label: 'Iran' },
  { id: 'flag-ie', url: 'https://flagcdn.com/w160/ie.png', label: 'Irlande' },
  { id: 'flag-is', url: 'https://flagcdn.com/w160/is.png', label: 'Islande' },
  { id: 'flag-il', url: 'https://flagcdn.com/w160/il.png', label: 'Israël' },
  { id: 'flag-it', url: 'https://flagcdn.com/w160/it.png', label: 'Italie' },
  { id: 'flag-jm', url: 'https://flagcdn.com/w160/jm.png', label: 'Jamaïque' },
  { id: 'flag-jp', url: 'https://flagcdn.com/w160/jp.png', label: 'Japon' },
  { id: 'flag-jo', url: 'https://flagcdn.com/w160/jo.png', label: 'Jordanie' },
  { id: 'flag-kz', url: 'https://flagcdn.com/w160/kz.png', label: 'Kazakhstan' },
  { id: 'flag-ke', url: 'https://flagcdn.com/w160/ke.png', label: 'Kenya' },
  { id: 'flag-kg', url: 'https://flagcdn.com/w160/kg.png', label: 'Kirghizistan' },
  { id: 'flag-ki', url: 'https://flagcdn.com/w160/ki.png', label: 'Kiribati' },
  { id: 'flag-kw', url: 'https://flagcdn.com/w160/kw.png', label: 'Koweït' },
  { id: 'flag-la', url: 'https://flagcdn.com/w160/la.png', label: 'Laos' },
  { id: 'flag-ls', url: 'https://flagcdn.com/w160/ls.png', label: 'Lesotho' },
  { id: 'flag-lv', url: 'https://flagcdn.com/w160/lv.png', label: 'Lettonie' },
  { id: 'flag-lb', url: 'https://flagcdn.com/w160/lb.png', label: 'Liban' },
  { id: 'flag-lr', url: 'https://flagcdn.com/w160/lr.png', label: 'Liberia' },
  { id: 'flag-ly', url: 'https://flagcdn.com/w160/ly.png', label: 'Libye' },
  { id: 'flag-li', url: 'https://flagcdn.com/w160/li.png', label: 'Liechtenstein' },
  { id: 'flag-lt', url: 'https://flagcdn.com/w160/lt.png', label: 'Lituanie' },
  { id: 'flag-lu', url: 'https://flagcdn.com/w160/lu.png', label: 'Luxembourg' },
  { id: 'flag-mk', url: 'https://flagcdn.com/w160/mk.png', label: 'Macédoine du Nord' },
  { id: 'flag-mg', url: 'https://flagcdn.com/w160/mg.png', label: 'Madagascar' },
  { id: 'flag-my', url: 'https://flagcdn.com/w160/my.png', label: 'Malaisie' },
  { id: 'flag-mw', url: 'https://flagcdn.com/w160/mw.png', label: 'Malawi' },
  { id: 'flag-mv', url: 'https://flagcdn.com/w160/mv.png', label: 'Maldives' },
  { id: 'flag-ml', url: 'https://flagcdn.com/w160/ml.png', label: 'Mali' },
  { id: 'flag-mt', url: 'https://flagcdn.com/w160/mt.png', label: 'Malte' },
  { id: 'flag-ma', url: 'https://flagcdn.com/w160/ma.png', label: 'Maroc' },
  { id: 'flag-mu', url: 'https://flagcdn.com/w160/mu.png', label: 'Maurice' },
  { id: 'flag-mr', url: 'https://flagcdn.com/w160/mr.png', label: 'Mauritanie' },
  { id: 'flag-mx', url: 'https://flagcdn.com/w160/mx.png', label: 'Mexique' },
  { id: 'flag-fm', url: 'https://flagcdn.com/w160/fm.png', label: 'Micronésie' },
  { id: 'flag-md', url: 'https://flagcdn.com/w160/md.png', label: 'Moldavie' },
  { id: 'flag-mc', url: 'https://flagcdn.com/w160/mc.png', label: 'Monaco' },
  { id: 'flag-mn', url: 'https://flagcdn.com/w160/mn.png', label: 'Mongolie' },
  { id: 'flag-me', url: 'https://flagcdn.com/w160/me.png', label: 'Monténégro' },
  { id: 'flag-mz', url: 'https://flagcdn.com/w160/mz.png', label: 'Mozambique' },
  { id: 'flag-na', url: 'https://flagcdn.com/w160/na.png', label: 'Namibie' },
  { id: 'flag-nr', url: 'https://flagcdn.com/w160/nr.png', label: 'Nauru' },
  { id: 'flag-np', url: 'https://flagcdn.com/w160/np.png', label: 'Népal' },
  { id: 'flag-ni', url: 'https://flagcdn.com/w160/ni.png', label: 'Nicaragua' },
  { id: 'flag-ne', url: 'https://flagcdn.com/w160/ne.png', label: 'Niger' },
  { id: 'flag-ng', url: 'https://flagcdn.com/w160/ng.png', label: 'Nigeria' },
  { id: 'flag-no', url: 'https://flagcdn.com/w160/no.png', label: 'Norvège' },
  { id: 'flag-nz', url: 'https://flagcdn.com/w160/nz.png', label: 'Nouvelle-Zélande' },
  { id: 'flag-om', url: 'https://flagcdn.com/w160/om.png', label: 'Oman' },
  { id: 'flag-ug', url: 'https://flagcdn.com/w160/ug.png', label: 'Ouganda' },
  { id: 'flag-uz', url: 'https://flagcdn.com/w160/uz.png', label: 'Ouzbékistan' },
  { id: 'flag-pk', url: 'https://flagcdn.com/w160/pk.png', label: 'Pakistan' },
  { id: 'flag-pw', url: 'https://flagcdn.com/w160/pw.png', label: 'Palaos' },
  { id: 'flag-ps', url: 'https://flagcdn.com/w160/ps.png', label: 'Palestine' },
  { id: 'flag-pa', url: 'https://flagcdn.com/w160/pa.png', label: 'Panama' },
  { id: 'flag-pg', url: 'https://flagcdn.com/w160/pg.png', label: 'Papouasie-Nouvelle-Guinée' },
  { id: 'flag-py', url: 'https://flagcdn.com/w160/py.png', label: 'Paraguay' },
  { id: 'flag-nl', url: 'https://flagcdn.com/w160/nl.png', label: 'Pays-Bas' },
  { id: 'flag-pe', url: 'https://flagcdn.com/w160/pe.png', label: 'Pérou' },
  { id: 'flag-ph', url: 'https://flagcdn.com/w160/ph.png', label: 'Philippines' },
  { id: 'flag-pl', url: 'https://flagcdn.com/w160/pl.png', label: 'Pologne' },
  { id: 'flag-pt', url: 'https://flagcdn.com/w160/pt.png', label: 'Portugal' },
  { id: 'flag-qa', url: 'https://flagcdn.com/w160/qa.png', label: 'Qatar' },
  { id: 'flag-cf', url: 'https://flagcdn.com/w160/cf.png', label: 'République centrafricaine' },
  { id: 'flag-cd', url: 'https://flagcdn.com/w160/cd.png', label: 'République démocratique du Congo' },
  { id: 'flag-do', url: 'https://flagcdn.com/w160/do.png', label: 'République dominicaine' },
  { id: 'flag-cz', url: 'https://flagcdn.com/w160/cz.png', label: 'République tchèque' },
  { id: 'flag-ro', url: 'https://flagcdn.com/w160/ro.png', label: 'Roumanie' },
  { id: 'flag-gb', url: 'https://flagcdn.com/w160/gb.png', label: 'Royaume-Uni' },
  { id: 'flag-ru', url: 'https://flagcdn.com/w160/ru.png', label: 'Russie' },
  { id: 'flag-rw', url: 'https://flagcdn.com/w160/rw.png', label: 'Rwanda' },
  { id: 'flag-kn', url: 'https://flagcdn.com/w160/kn.png', label: 'Saint-Kitts-et-Nevis' },
  { id: 'flag-sm', url: 'https://flagcdn.com/w160/sm.png', label: 'Saint-Marin' },
  { id: 'flag-vc', url: 'https://flagcdn.com/w160/vc.png', label: 'Saint-Vincent-et-les-Grenadines' },
  { id: 'flag-lc', url: 'https://flagcdn.com/w160/lc.png', label: 'Sainte-Lucie' },
  { id: 'flag-sv', url: 'https://flagcdn.com/w160/sv.png', label: 'Salvador' },
  { id: 'flag-ws', url: 'https://flagcdn.com/w160/ws.png', label: 'Samoa' },
  { id: 'flag-st', url: 'https://flagcdn.com/w160/st.png', label: 'São Tomé-et-Principe' },
  { id: 'flag-sn', url: 'https://flagcdn.com/w160/sn.png', label: 'Sénégal' },
  { id: 'flag-rs', url: 'https://flagcdn.com/w160/rs.png', label: 'Serbie' },
  { id: 'flag-sc', url: 'https://flagcdn.com/w160/sc.png', label: 'Seychelles' },
  { id: 'flag-sl', url: 'https://flagcdn.com/w160/sl.png', label: 'Sierra Leone' },
  { id: 'flag-sg', url: 'https://flagcdn.com/w160/sg.png', label: 'Singapour' },
  { id: 'flag-sk', url: 'https://flagcdn.com/w160/sk.png', label: 'Slovaquie' },
  { id: 'flag-si', url: 'https://flagcdn.com/w160/si.png', label: 'Slovénie' },
  { id: 'flag-so', url: 'https://flagcdn.com/w160/so.png', label: 'Somalie' },
  { id: 'flag-sd', url: 'https://flagcdn.com/w160/sd.png', label: 'Soudan' },
  { id: 'flag-ss', url: 'https://flagcdn.com/w160/ss.png', label: 'Soudan du Sud' },
  { id: 'flag-lk', url: 'https://flagcdn.com/w160/lk.png', label: 'Sri Lanka' },
  { id: 'flag-se', url: 'https://flagcdn.com/w160/se.png', label: 'Suède' },
  { id: 'flag-ch', url: 'https://flagcdn.com/w160/ch.png', label: 'Suisse' },
  { id: 'flag-sr', url: 'https://flagcdn.com/w160/sr.png', label: 'Suriname' },
  { id: 'flag-sy', url: 'https://flagcdn.com/w160/sy.png', label: 'Syrie' },
  { id: 'flag-tj', url: 'https://flagcdn.com/w160/tj.png', label: 'Tadjikistan' },
  { id: 'flag-tz', url: 'https://flagcdn.com/w160/tz.png', label: 'Tanzanie' },
  { id: 'flag-td', url: 'https://flagcdn.com/w160/td.png', label: 'Tchad' },
  { id: 'flag-th', url: 'https://flagcdn.com/w160/th.png', label: 'Thaïlande' },
  { id: 'flag-tl', url: 'https://flagcdn.com/w160/tl.png', label: 'Timor oriental' },
  { id: 'flag-tg', url: 'https://flagcdn.com/w160/tg.png', label: 'Togo' },
  { id: 'flag-to', url: 'https://flagcdn.com/w160/to.png', label: 'Tonga' },
  { id: 'flag-tt', url: 'https://flagcdn.com/w160/tt.png', label: 'Trinité-et-Tobago' },
  { id: 'flag-tn', url: 'https://flagcdn.com/w160/tn.png', label: 'Tunisie' },
  { id: 'flag-tm', url: 'https://flagcdn.com/w160/tm.png', label: 'Turkménistan' },
  { id: 'flag-tr', url: 'https://flagcdn.com/w160/tr.png', label: 'Turquie' },
  { id: 'flag-tv', url: 'https://flagcdn.com/w160/tv.png', label: 'Tuvalu' },
  { id: 'flag-ua', url: 'https://flagcdn.com/w160/ua.png', label: 'Ukraine' },
  { id: 'flag-uy', url: 'https://flagcdn.com/w160/uy.png', label: 'Uruguay' },
  { id: 'flag-vu', url: 'https://flagcdn.com/w160/vu.png', label: 'Vanuatu' },
  { id: 'flag-va', url: 'https://flagcdn.com/w160/va.png', label: 'Vatican' },
  { id: 'flag-ve', url: 'https://flagcdn.com/w160/ve.png', label: 'Venezuela' },
  { id: 'flag-vn', url: 'https://flagcdn.com/w160/vn.png', label: 'Viêt Nam' },
  { id: 'flag-ye', url: 'https://flagcdn.com/w160/ye.png', label: 'Yémen' },
  { id: 'flag-zm', url: 'https://flagcdn.com/w160/zm.png', label: 'Zambie' },
  { id: 'flag-zw', url: 'https://flagcdn.com/w160/zw.png', label: 'Zimbabwe' },
];

export const FANZ_AVATARS = ALL_FANZ.map(f => ({
  id: `avatar-${f.id}`,
  url: f.image,
  label: f.name
}));

export const SKIN_AVATARS = ALL_FANZ.flatMap(f => 
  (f.skins || []).map(skin => ({
    id: `avatar-skin-${skin.id}`,
    url: skin.imageUrl,
    label: `${f.name} - ${skin.name}`
  }))
);

export const LANGUAGES = [
  { code: 'fr', label: 'Français' },
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'it', label: 'Italiano' },
  { code: 'de', label: 'Deutsch' },
  { code: 'pt', label: 'Português' },
];
