import type { Card } from '../types.ts';

export const BASE_CARDS: Card[] = [
  {
    id: 'base_1',
    name: 'Cri de Guerre',
    type: 'bonus',
    rarity: 'common',
    energyCost: 2,
    fervorValue: 5,
    description: 'Pousse la corde de 5% vers votre équipe.',
    effects: [{ type: 'push_rope', value: 5 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_1.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_2',
    name: 'Fumigène',
    type: 'malus',
    rarity: 'common',
    energyCost: 3,
    fervorValue: 0,
    description: 'Floute la vue de l\'adversaire pendant 5 secondes.',
    effects: [{ type: 'blur_view', duration: 5 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_2.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_3',
    name: 'Tifo Géant',
    type: 'bonus',
    rarity: 'rare',
    energyCost: 5,
    fervorValue: 12,
    description: 'Pousse la corde de 12% vers votre équipe.',
    effects: [{ type: 'push_rope', value: 12 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_3.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_4',
    name: 'Chant de Ralliement',
    type: 'bonus',
    rarity: 'common',
    energyCost: 3,
    fervorValue: 0,
    description: 'Rend 4 points d\'excitation.',
    effects: [{ type: 'refill_energy', value: 4 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_4.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_5',
    name: 'Vuvuzela',
    category: 'Objet',
    type: 'malus',
    rarity: 'common',
    energyCost: 4,
    fervorValue: 0,
    description: 'Vole 3 points d\'excitation à l\'adversaire.',
    effects: [{ type: 'drain_energy', value: 3 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_5.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_6',
    name: 'Blackout',
    type: 'malus',
    rarity: 'epic',
    energyCost: 6,
    fervorValue: 0,
    description: 'Fait disparaître le bouton de l\'adversaire pendant 4 secondes.',
    effects: [{ type: 'hide_button', duration: 4 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_6.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_7',
    name: 'Mini-Ballon',
    type: 'malus',
    rarity: 'rare',
    energyCost: 4,
    fervorValue: 0,
    description: 'Réduit la taille du bouton adverse pendant 6 secondes.',
    effects: [{ type: 'shrink_button', duration: 6 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_7.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_8',
    name: 'Vent de Panique',
    type: 'malus',
    rarity: 'epic',
    energyCost: 5,
    fervorValue: 0,
    description: 'Le bouton adverse se déplace pendant 8 secondes.',
    effects: [{ type: 'move_button', duration: 8 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_8.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_9',
    name: 'Carton Rouge',
    type: 'malus',
    rarity: 'epic',
    energyCost: 7,
    fervorValue: 0,
    description: 'Gèle le bouton adverse pendant 3 secondes.',
    effects: [{ type: 'freeze_button', duration: 3 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_9.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_10',
    name: 'Olé!',
    type: 'neutral',
    rarity: 'rare',
    energyCost: 4,
    fervorValue: 0,
    description: 'Mélange la main de l\'adversaire.',
    effects: [{ type: 'shuffle_deck' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_10.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_11',
    name: 'Coup de Sifflet',
    type: 'malus',
    rarity: 'common',
    energyCost: 2,
    fervorValue: 0,
    description: 'Cache le score pendant 7 secondes.',
    effects: [{ type: 'hide_score', duration: 7 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_11.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_12',
    name: 'Hors-jeu',
    type: 'malus',
    rarity: 'epic',
    energyCost: 6,
    fervorValue: 0,
    description: 'Défausse une carte de la main adverse.',
    effects: [{ type: 'discard_enemy_cards' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_12.png',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'double-ferveur',
    name: 'Double Ferveur',
    description: 'Vos clics comptent double pendant 5 secondes.',
    rarity: 'rare',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 8,
    effects: [{ type: 'double_points', duration: 5 }],
    imageUrl: 'https://thebestfan.online/public/duel/double-ferveur.png',
    fanzIds: []
  },
  {
    id: 'bouclier-divin',
    name: 'Bouclier Divin',
    description: 'Vous protège du prochain malus adverse.',
    rarity: 'epic',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 6,
    effects: [{ type: 'shield' }],
    imageUrl: 'https://thebestfan.online/public/duel/bouclier-divin.png',
    fanzIds: []
  },
  {
    id: 'seisme',
    name: 'Séisme',
    description: 'Fait trembler l\'écran de l\'adversaire.',
    rarity: 'rare',
    type: 'malus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'earthquake', duration: 3 }],
    imageUrl: 'https://thebestfan.online/public/duel/seisme.png',
    fanzIds: []
  },
  {
    id: 'miroir-magique',
    name: 'Miroir Magique',
    description: 'Renvoie le prochain malus à l\'adversaire.',
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 5,
    fervorValue: 10,
    effects: [{ type: 'mirror' }],
    imageUrl: 'https://thebestfan.online/public/duel/miroir-magique.png',
    fanzIds: []
  },
  {
    id: 'boutons-fantomes',
    name: 'Boutons Fantômes',
    description: 'Affiche de faux boutons sur l\'écran adverse.',
    rarity: 'epic',
    type: 'malus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'fake_buttons', duration: 5 }],
    imageUrl: 'https://thebestfan.online/public/duel/boutons-fantomes.png',
    fanzIds: []
  },
  {
    id: 'unlock_skill_1',
    name: 'Force Brute',
    type: 'bonus',
    rarity: 'rare',
    energyCost: 4,
    fervorValue: 15,
    description: 'Pousse la corde de 15%. Requis: Force Niv. 3',
    effects: [{ type: 'push_rope', value: 15 }],
    imageUrl: 'https://thebestfan.online/public/duel/unlock_skill_1.png',
    unlockRequirements: [{ type: 'skill', skillName: 'force', minLevel: 3 }]
  },
  {
    id: 'unlock_ferveur_1',
    name: 'Aura de Ferveur',
    type: 'bonus',
    rarity: 'epic',
    energyCost: 5,
    fervorValue: 0,
    description: 'Double la régénération d\'excitation. Requis: Ferveur Niv. 2',
    effects: [{ type: 'energy_regen_boost', duration: 10 }],
    imageUrl: 'https://thebestfan.online/public/duel/unlock_ferveur_1.png',
    unlockRequirements: [{ type: 'ferveur', minLevel: 2 }]
  },
  {
    id: 'unlock_rank_1',
    name: 'Légende du Fanz',
    type: 'bonus',
    rarity: 'legendary',
    energyCost: 8,
    fervorValue: 25,
    description: 'Pousse la corde de 25%. Requis: Rang Fanz 5',
    effects: [{ type: 'push_rope', value: 25 }],
    imageUrl: 'https://thebestfan.online/public/duel/unlock_rank_1.png',
    unlockRequirements: [{ type: 'rank', minLevel: 5 }]
  },
  {
    id: 'mimic',
    name: 'Imitation',
    description: 'Copie le dernier malus joué par l\'adversaire.',
    rarity: 'legendary',
    type: 'neutral',
    energyCost: 6,
    fervorValue: 0,
    effects: [{ type: 'mimic' }],
    imageUrl: 'https://thebestfan.online/public/duel/mimic.png',
    fanzIds: []
  },
  {
    id: 'lucky_draw',
    name: 'Main de la Chance',
    description: 'Remplace une carte de votre main par une carte aléatoire de rareté supérieure.',
    rarity: 'epic',
    type: 'bonus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'lucky_draw' }],
    imageUrl: 'https://thebestfan.online/public/duel/lucky_draw.png',
    fanzIds: []
  },
  {
    id: 'swap_hands',
    name: 'Échange Standard',
    description: 'Échange votre main avec celle de l\'adversaire.',
    rarity: 'legendary',
    type: 'neutral',
    energyCost: 7,
    fervorValue: 0,
    effects: [{ type: 'swap_hands' }],
    imageUrl: 'https://thebestfan.online/public/duel/swap_hands.png',
    fanzIds: []
  },
  {
    id: 'fanz-001-poussette',
    name: "L'Aura de la Poussette",
    description: "Protection ultime : vous êtes immunisé contre le prochain malus joué par votre adversaire.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 0,
    effects: [{ type: 'shield' }],
    imageUrl: 'https://cdn.leonardo.ai/users/e39893af-e6c8-477d-bbbf-f9ed93c9d74e/image_generations/9264c8d1-d2c6-4d04-bbb7-5c5ebf899eab/Leonardo_Phoenix_10_A_close_up_of_a_baby_stroller_decked_out_i_3.jpg',
    fanzIds: ['fanz-001']
  },
  {
    id: 'fanz-001-regurgitation',
    name: "Régurgitation sur le Maillot",
    description: "Le bébé ruine son équipement. Déconcentre l'adversaire et lui supprime 3 points d'excitation instantanément.",
    rarity: 'rare',
    type: 'malus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'drain_energy', value: 3 }],
    imageUrl: 'https://cdn.leonardo.ai/users/e39893af-e6c8-477d-bbbf-f9ed93c9d74e/image_generations/ffcf0b74-325d-4f7f-ba00-2f1687f893e5/Leonardo_Phoenix_10_A_close_up_of_a_tastylooking_stain_on_a_ne_2.jpg',
    fanzIds: ['fanz-001']
  },
  {
    id: 'fanz-001-tetine',
    name: "La Tétine Tombe par Terre",
    description: "Le stade s'arrête face au drame ! Gèle les actions de l'adversaire pendant 5 secondes le temps de la retrouver.",
    rarity: 'epic',
    type: 'neutral',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'freeze_button', duration: 5 }],
    imageUrl: 'https://cdn.leonardo.ai/users/e39893af-e6c8-477d-bbbf-f9ed93c9d74e/image_generations/0e1b10e4-ff2e-4b47-bbf1-8dc17eb73e6a/Leonardo_Phoenix_10_A_pacifier_with_a_football_pattern_lying_2.jpg',
    fanzIds: ['fanz-001']
  },
  {
    id: 'base_steal_energy',
    name: "Vol d'Excitation",
    description: "Siphonne 2 points d'excitation à l'adversaire et vous les donne.",
    rarity: 'rare',
    type: 'bonus',
    energyCost: 2,
    fervorValue: 0,
    effects: [{ type: 'steal_energy', value: 2 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_steal_energy.png',
    fanzIds: []
  },
  {
    id: 'base_cleanse',
    name: "Purge",
    description: "Annule instantanément tous vos malus actifs (bouton flou, caché...).",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'cleanse' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_cleanse.png',
    fanzIds: []
  },
  {
    id: 'base_vampirism',
    name: "Vampirisme",
    description: "Pendant 5 secondes, vos clics drainent légèrement la ferveur de l'adversaire.",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 6,
    fervorValue: 0,
    effects: [{ type: 'vampirism', duration: 5 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_vampirism.png',
    fanzIds: []
  },
  {
    id: 'base_fog_of_war',
    name: "Cécité Tactique",
    description: "Masque l'interface de l'adversaire de façon chaotique pendant 6 secondes.",
    rarity: 'epic',
    type: 'malus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'fog_of_war', duration: 6 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_fog_of_war.png',
    fanzIds: []
  },
  {
    id: 'base_frenzy',
    name: "Frénésie",
    description: "Pendant 3 secondes, vos cartes ne coûtent plus aucune énergie !",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 9,
    fervorValue: 0,
    effects: [{ type: 'frenzy', duration: 3 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_frenzy.png',
    fanzIds: []
  },
  {
    id: 'base_sabotage',
    name: "Sabotage",
    description: "La FAUTE PROFESSIONNELLE ! La prochaine carte jouée par l'adversaire verra son coût doublé.",
    rarity: 'rare',
    type: 'malus',
    energyCost: 4,
    fervorValue: 0,
    effects: [{ type: 'sabotage' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_sabotage.png',
    fanzIds: []
  },
  {
    id: 'base_immunity',
    name: "Immunité Diplomatique",
    description: "Vous êtes insensible aux malus extérieurs pendant 8 secondes.",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 8,
    fervorValue: 0,
    effects: [{ type: 'immunity', duration: 8 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_immunity.png',
    fanzIds: []
  },
  {
    id: 'base_critical_strike',
    name: "Frappe Critique",
    description: "Votre prochain clic comptera 5 fois plus !",
    rarity: 'rare',
    type: 'bonus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'critical_strike' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_critical_strike.png',
    fanzIds: []
  },
  {
    id: 'base_momentum',
    name: "Momentum",
    description: "La foule est avec vous ! La ferveur augmente toute seule pendant 5 secondes.",
    rarity: 'epic',
    type: 'neutral',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'momentum', duration: 5 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_momentum.png',
    fanzIds: []
  },
  {
    id: 'base_overload',
    name: "Surcharge",
    description: "Faites le plein d'énergie (+10) instantanément, mais perdez 5% de ferveur au passage.",
    rarity: 'epic',
    type: 'neutral',
    energyCost: 0,
    fervorValue: -5,
    effects: [{ type: 'overload' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_overload.png',
    fanzIds: []
  },
  {
    id: 'base_invert_rope',
    name: "Retournement de Veste",
    description: "Panique totale ! La corde s'inverse. Si vous étiez mené, vous prenez l'avantage. (Reste centré si proche de 50%).",
    rarity: 'legendary',
    type: 'neutral',
    energyCost: 10,
    fervorValue: 0,
    effects: [{ type: 'invert_rope' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_invert_rope.png',
    fanzIds: []
  },
  {
    id: 'base_blackout',
    name: "Coupure de Courant",
    description: "Plonge le stade adverse dans le noir complet pendant 8 secondes !",
    rarity: 'epic',
    type: 'malus',
    energyCost: 6,
    fervorValue: 0,
    effects: [{ type: 'blackout', duration: 8 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_blackout.png',
    fanzIds: []
  },
  {
    id: 'base_curse',
    name: "Malédiction Vaudou",
    description: "La prochaine carte de l'adversaire coûtera 3 énergies supplémentaires !",
    rarity: 'rare',
    type: 'malus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'curse' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_curse.png',
    fanzIds: []
  },
  {
    id: 'base_blessing',
    name: "Bénédiction du Kop",
    description: "Toutes vos cartes coûtent 2 d'énergie en moins pendant 10 secondes.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'blessing', duration: 10 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_blessing.png',
    fanzIds: []
  },
  {
    id: 'base_confetti',
    name: "Avalanche de Confettis",
    description: "Inonde l'écran de l'adversaire de confettis pendant 7 secondes, réduisant la visibilité.",
    rarity: 'common',
    type: 'malus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'confetti', duration: 7 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_confetti.png',
    fanzIds: []
  },
  {
    id: 'base_golden_goal',
    name: "Balle de Match",
    description: "Votre prochain clic a un impact dévastateur (x15) !!",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 8,
    fervorValue: 0,
    effects: [{ type: 'golden_goal' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_golden_goal.png',
    fanzIds: []
  },
  {
    id: 'base_hypnosis',
    name: "Hypnose Collective",
    description: "Pendant 4 secondes, l'adversaire clique POUR votre équipe sans s'en rendre compte !",
    rarity: 'legendary',
    type: 'malus',
    energyCost: 10,
    fervorValue: 0,
    effects: [{ type: 'hypnosis', duration: 4 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_hypnosis.png',
    fanzIds: []
  },
  {
    id: 'base_lourd_ballon_cuir',
    name: "Le Lourd Ballon en Cuir",
    category: 'Objet',
    description: "S'équipe sur un supporter. Confère un bonus d'attaque, mais a 50% de chances d'\"Assommer\" la cible adverse (qui passe son prochain tour) tellement le ballon gorgé d'eau is lourd.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 5,
    fervorValue: 0,
    effects: [
      { type: 'heavy_ball_boost', duration: 12 },
      { type: 'stun', duration: 5 }
    ],
    imageUrl: 'https://thebestfan.online/public/duel/base_heavy_ball.png',
    fanzIds: []
  },
  {
    id: 'base_tacle_gorge',
    name: "Tacle à la Gorge (Sans la VAR !)",
    description: "Une attaque physique pure et dure. Inflige de lourds dégâts directs et ignore l'armure de l'adversaire. \"À l'époque, l'arbitre laissait jouer !\"",
    rarity: 'epic',
    type: 'malus',
    energyCost: 6,
    fervorValue: 25,
    effects: [
      { type: 'throat_tackle', value: 25 }
    ],
    imageUrl: 'https://thebestfan.online/public/duel/base_throat_tackle.png',
    fanzIds: []
  },
  {
    id: 'base_charge_mammouth',
    name: "Charge de Mammouth",
    description: "Un envahissement de terrain bestial. Détruit instantanément tous les Boucliers ou cartes de défense posées par l'adversaire sur sa ligne de front.",
    rarity: 'epic',
    type: 'malus',
    energyCost: 5,
    fervorValue: 10,
    effects: [{ type: 'mammoth_charge' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_mammoth_charge.png',
    fanzIds: []
  },
  {
    id: 'base_tambour_os_mascotte',
    name: "Tambour en Os de Mascotte",
    category: 'Objet',
    description: "Un bruit assourdissant qui 'Intimide' l'adversaire, réduisant sa puissance d'attaque/clic de 50% pendant 8 secondes.",
    rarity: 'rare',
    type: 'malus',
    energyCost: 4,
    fervorValue: 0,
    effects: [{ type: 'mascot_bone_drum', duration: 8 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_mascot_bone_drum.png',
    fanzIds: []
  },
  {
    id: 'base_mur_echarpes_boucliers',
    name: "Mur d'Écharpes et de Boucliers",
    description: "La tribune se transforme en forteresse. Pendant 12 secondes, tous les dégâts d'énergie ou debuffs subis sont divisés par deux.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 6,
    fervorValue: 0,
    effects: [{ type: 'scarves_wall', duration: 12 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_scarves_wall.png',
    fanzIds: []
  },
  {
    id: 'base_ost_du_virage',
    name: "L'Ost du Virage",
    description: "Le cor de ralliement sonne. Permet d'invoquer immédiatement un supporter commun supplémentaire depuis ta pioche pour faire le surnombre.",
    rarity: 'rare',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 5,
    effects: [{ type: 'virage_host', value: 1 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_virage_host.png',
    fanzIds: []
  },
  {
    id: 'base_clapping_odin',
    name: "Chant : Le Clapping d'Odin",
    category: 'Chant',
    description: "Un rythme lent qui s'accélère. À chaque fin de tour où cette carte reste sur le terrain, tes supporters gagnent +1 en Puissance. Si l'adversaire ne détruit pas la carte, le rythme devient dévastateur.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 5,
    fervorValue: 5,
    effects: [{ type: 'clapping_odin', duration: 15 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_clapping_odin.png',
    fanzIds: []
  },
  {
    id: 'base_corne_drakkar',
    name: "Objet : Corne de Brume de Drakkar",
    category: 'Objet',
    description: "Un son si puissant qu'il \"assourdit\" le camp adverse. L'ennemi ne peut jouer aucune carte \"Chant\" ou \"Sort\" à son prochain tour.",
    rarity: 'rare',
    type: 'malus',
    energyCost: 4,
    fervorValue: 0,
    effects: [{ type: 'corne_drakkar', duration: 10 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_corne_drakkar.png',
    fanzIds: []
  },
  {
    id: 'base_abordage_parcage',
    name: "Action : Abordage du Parcage Visiteur",
    category: 'Action',
    description: "Permet de voler une carte \"Objet\" (mégaphone, tambour, ballon...) actuellement dans la main adverse pour l'ajouter à ta main.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 3,
    fervorValue: 5,
    effects: [{ type: 'steal_object_card' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_abordage_parcage.png',
    fanzIds: []
  },
  {
    id: 'base_perroquet_insolent',
    name: "Compagnon : Perroquet Insolent",
    category: 'Compagnon',
    description: "Se pose sur l'épaule de ton supporter et insulte l'arbitre. Possède la compétence \"Provocation\" (Taunt) : la prochaine action ou attaque négative adverse est bloquée ou subie par le perroquet.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 0,
    effects: [{ type: 'parrot_taunt', duration: 15 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_perroquet_insolent.png',
    fanzIds: []
  },
  {
    id: 'base_pumpkin_fog',
    name: "Objet : Fumigène Citrouille Toxique",
    category: 'Objet',
    description: "Dégage un épais brouillard orange. L'adversaire est \"Aveuglé\" pendant 12s : ses clics ont 50% de chances d'échouer (il tape dans le vide).",
    rarity: 'epic',
    type: 'malus',
    energyCost: 4,
    fervorValue: 0,
    effects: [{ type: 'pumpkin_fog', duration: 12 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_pumpkin_fog.png',
    fanzIds: []
  },
  {
    id: 'base_locker_room_curse',
    name: "Piège : La Malédiction des Vestiaires",
    category: 'Piège',
    description: "Se joue face cachée. Le prochain supporter posé par l'adversaire (sa prochaine carte jouée) arrive avec la peur au ventre : sa valeur de Ferveur est divisée par deux.",
    rarity: 'rare',
    type: 'malus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'locker_room_curse' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_locker_room_curse.png',
    fanzIds: []
  },
  {
    id: 'base_luminescent_standard',
    name: "Objet : L'Étendard Luminescent",
    category: 'Objet',
    description: "Une bannière de corner tissée de magie. Immunise contre toutes les altérations d'état (étourdissement, peur, vol, citrouille...) pour 15s.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'luminescent_standard', duration: 15 }],
    imageUrl: 'https://thebestfan.online/public/duel/base_luminescent_standard.png',
    fanzIds: []
  },
  {
    id: 'base_buvette_grail',
    name: "Consommable : Le Graal de la Buvette",
    category: 'Consommable',
    description: "Une chope dorée mystique. Soigne la déroute (ramène la corde à 50%) et confère un Bouclier Divin absorbant la prochaine attaque.",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 0,
    effects: [{ type: 'buvette_grail' }, { type: 'shield' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_buvette_grail.png',
    fanzIds: []
  },
  {
    id: 'base_var_illusion',
    name: "Sortilège : Illusion de la VAR",
    category: 'Sort',
    description: "La boule de cristal du sorcier montre un hors-jeu imaginaire ! Contre et annule entièrement la dernière carte 'Action' jouée par l'adversaire.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'var_illusion' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_var_illusion.png',
    fanzIds: []
  },
  {
    id: 'base_grimoire_chants',
    name: "Objet : Grimoire des Chants Oubliés",
    category: 'Objet',
    description: "Un livre très ancien. Permet de choisir et de replacer dans sa main un 'Chant' ou 'Sort' de sa défausse.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 2,
    fervorValue: 0,
    effects: [{ type: 'grimoire_chants' }],
    imageUrl: 'https://thebestfan.online/public/duel/base_grimoire_chants.png',
    fanzIds: []
  },
  {
    id: 'base_chainsaw_megaphone',
    name: "Objet : Le Mégaphone-Tronçonneuse",
    category: 'Objet',
    description: "Instable mais surpuissant. Détruit instantanément l'armure de la cible (bouclier divin) et inflige d'énormes dégâts (+24% de ferveur pour vous), mais inflige 1 d'excitation de dégât de recul.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 24,
    effects: [{ type: 'chainsaw_megaphone' }],
    imageUrl: 'https://thebestfan.online/public/images/megaphone_chainsaw.png',
    fanzIds: []
  },
  {
    id: 'base_burning_seats',
    name: "Environnement : Pluie de Sièges Enflammés",
    category: 'Environnement',
    description: "Des sièges en feu pleuvent sur le stade. Détruit TOUS les bonus, protections et compagnons actifs sur le terrain pour les deux équipes, et défausse 1 carte non protégée de chaque main !",
    rarity: 'legendary',
    type: 'malus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'burning_seats' }],
    imageUrl: 'https://thebestfan.online/public/images/burning_seats.png',
    fanzIds: []
  },
  {
    id: 'base_var_temporelle',
    name: "Action Légendaire : VAR Temporelle",
    category: 'Action',
    description: "Arbitrage Vidéo 4D : rembobine le match ! Ramène le plateau de jeu exactement à l'état où il était au début du tour précédent.",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 6,
    fervorValue: 0,
    effects: [{ type: 'var_temporelle' }],
    imageUrl: 'https://thebestfan.online/public/images/var_temporelle.png',
    fanzIds: []
  },
  {
    id: 'base_tifo_holographique',
    name: "Défense : Tifo Holographique 3D",
    category: 'Objet',
    description: "Projette la mascotte du club en laser géant. Absorbe la prochaine grosse attaque adverse et lui renvoie la moitié de sa ferveur sous forme d'onde de choc.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'tifo_holographique' }],
    imageUrl: 'https://thebestfan.online/public/images/tifo_holographic.png',
    fanzIds: []
  },
  {
    id: 'base_capo_megaphone',
    name: "Objet Unique : Le Mégaphone du Capo",
    category: 'Objet',
    description: "Relique sacrée. Seul un Ultra peut s'en équiper. Tant qu'il est actif (15s), il double la puissance de ferveur de vos clics et de TOUTES vos autres cartes.",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 0,
    effects: [{ type: 'capo_megaphone', duration: 15 }],
    imageUrl: 'https://thebestfan.online/public/images/capo_megaphone.png',
    fanzIds: []
  },
  {
    id: 'base_craquage_massif',
    name: "Action Ultime : Craquage Massif",
    category: 'Action',
    description: "Craquage de la 90ème minute ! 100 fumigènes embrasent le stade. Inflige de très lourds dégâts de zone (+30% de ferveur pour vous) et plonge vos cartes dans un épais brouillard rouge protecteur.",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 6,
    fervorValue: 30,
    effects: [{ type: 'craquage_massif', duration: 10 }],
    imageUrl: 'https://thebestfan.online/public/images/craquage_massif.png',
    fanzIds: []
  },
  {
    id: 'base_vol_ballon',
    name: 'Vol de Ballon',
    type: 'malus',
    rarity: 'rare',
    energyCost: 4,
    fervorValue: 0,
    description: 'Doggo sprinte sur la pelouse au pire moment et chipe le ballon. La carte adverse ciblée est déstabilisée : elle passe son tour et voit son attaque réduite à 0 pour la prochaine manche.',
    effects: [{ type: 'vol_ballon', duration: 6 }],
    imageUrl: 'https://thebestfan.online/public/images/vol_ballon.png',
    fanzIds: []
  },
  {
    id: 'base_regard_chien_battu',
    name: 'Regard de Chien Battu',
    type: 'bonus',
    rarity: 'epic',
    energyCost: 3,
    fervorValue: 0,
    description: "Doggo s'assoit et fait ses yeux les plus tristes et mignons à l'arbitre. Annule instantanément le dernier malus ou carton reçu par l'une de vos cartes alliées, et redonne un bonus d'Endurance.",
    effects: [{ type: 'regard_chien_battu', value: 30 }],
    imageUrl: 'https://thebestfan.online/public/images/regard_chien_battu.png',
    fanzIds: []
  },
  {
    id: 'base_zoomies_chaos',
    name: 'Les Zoomies du Chaos',
    type: 'neutral',
    rarity: 'epic',
    energyCost: 5,
    fervorValue: 0,
    description: 'Pris d\'un quart d\'heure de folie, Doggo court à 100 km/h aux quatre coins du plateau en aboyant. La panique s\'installe : les deux joueurs doivent immédiatement défausser une carte au hasard de leur main et en piocher une nouvelle.',
    effects: [{ type: 'zoomies_chaos' }],
    imageUrl: 'https://thebestfan.online/public/images/zoomies_chaos.png',
    fanzIds: []
  },
  {
    id: 'base_script_with_me',
    name: 'Le Script est avec moi',
    category: 'Action',
    type: 'bonus',
    rarity: 'epic',
    energyCost: 4,
    fervorValue: 0,
    description: 'Annulez la dernière attaque réussie de l\'adversaire. Le "script" algorithmique du jeu a décidé que le ballon devait rebondir miraculeusement dans vos pieds.',
    effects: [{ type: 'cancel_last_attack' }],
    imageUrl: 'https://thebestfan.online/public/images/script_with_me.png',
    fanzIds: []
  },
  {
    id: 'base_rage_quit',
    name: 'Rage Quit Téléphonique',
    category: 'Piège',
    type: 'malus',
    rarity: 'epic',
    energyCost: 5,
    fervorValue: 0,
    description: 'Votre Spécialiste vient d\'encaisser un but gag. Il éteint la console de rage. Défaussez toutes les cartes "Action Rapide" de votre main et passez le tour.',
    effects: [{ type: 'rage_quit_discard', duration: 6 }],
    imageUrl: 'https://thebestfan.online/public/images/rage_quit.png',
    fanzIds: []
  },
  {
    id: 'base_meta_update',
    name: 'Mise à Jour des Stats (Nouvelle Méta)',
    category: 'Événement',
    type: 'neutral',
    rarity: 'epic',
    energyCost: 3,
    fervorValue: 0,
    description: 'Une nouvelle mise à jour vient de tomber. Les cartes ayant moins de 3 points en Attaque gagnent +2, celles ayant plus de 5 points perdent -2. Valable jusqu\'à la fin du tour.',
    effects: [{ type: 'meta_update', duration: 15 }],
    imageUrl: 'https://thebestfan.online/public/images/meta_update.png',
    fanzIds: []
  }
];
