import type { Card } from '../types.ts';

export const BASE_CARDS: Card[] = [
  {
    id: 'base_1',
    name: 'Cri de Guerre',
    type: 'bonus',
    rarity: 'common',
    energyCost: 2,
    fervorValue: 5,
    description: 'Pousse la corde de 5% vers votre équipe.',
    effects: [{ type: 'push_rope', value: 5 }],
    imageUrl: 'https://picsum.photos/seed/war/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_2',
    name: 'Fumigène',
    type: 'malus',
    rarity: 'common',
    energyCost: 3,
    fervorValue: 0,
    description: 'Floute la vue de l\'adversaire pendant 5 secondes.',
    effects: [{ type: 'blur_view', duration: 5 }],
    imageUrl: 'https://picsum.photos/seed/smoke/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_3',
    name: 'Tifo Géant',
    type: 'bonus',
    rarity: 'rare',
    energyCost: 5,
    fervorValue: 12,
    description: 'Pousse la corde de 12% vers votre équipe.',
    effects: [{ type: 'push_rope', value: 12 }],
    imageUrl: 'https://picsum.photos/seed/tifo/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_4',
    name: 'Chant de Ralliement',
    type: 'bonus',
    rarity: 'common',
    energyCost: 3,
    fervorValue: 0,
    description: 'Rend 4 points d\'excitation.',
    effects: [{ type: 'refill_energy', value: 4 }],
    imageUrl: 'https://picsum.photos/seed/chant/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_5',
    name: 'Vuvuzela',
    type: 'malus',
    rarity: 'common',
    energyCost: 4,
    fervorValue: 0,
    description: 'Vole 3 points d\'excitation à l\'adversaire.',
    effects: [{ type: 'drain_energy', value: 3 }],
    imageUrl: 'https://picsum.photos/seed/noise/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_6',
    name: 'Blackout',
    type: 'malus',
    rarity: 'epic',
    energyCost: 6,
    fervorValue: 0,
    description: 'Fait disparaître le bouton de l\'adversaire pendant 4 secondes.',
    effects: [{ type: 'hide_button', duration: 4 }],
    imageUrl: 'https://picsum.photos/seed/dark/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_7',
    name: 'Mini-Ballon',
    type: 'malus',
    rarity: 'rare',
    energyCost: 4,
    fervorValue: 0,
    description: 'Réduit la taille du bouton adverse pendant 6 secondes.',
    effects: [{ type: 'shrink_button', duration: 6 }],
    imageUrl: 'https://picsum.photos/seed/small/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_8',
    name: 'Vent de Panique',
    type: 'malus',
    rarity: 'epic',
    energyCost: 5,
    fervorValue: 0,
    description: 'Le bouton adverse se déplace pendant 8 secondes.',
    effects: [{ type: 'move_button', duration: 8 }],
    imageUrl: 'https://picsum.photos/seed/wind/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_9',
    name: 'Carton Rouge',
    type: 'malus',
    rarity: 'epic',
    energyCost: 7,
    fervorValue: 0,
    description: 'Gèle le bouton adverse pendant 3 secondes.',
    effects: [{ type: 'freeze_button', duration: 3 }],
    imageUrl: 'https://picsum.photos/seed/redcard/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_10',
    name: 'Olé!',
    type: 'neutral',
    rarity: 'rare',
    energyCost: 4,
    fervorValue: 0,
    description: 'Mélange la main de l\'adversaire.',
    effects: [{ type: 'shuffle_deck' }],
    imageUrl: 'https://picsum.photos/seed/ole/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_11',
    name: 'Coup de Sifflet',
    type: 'malus',
    rarity: 'common',
    energyCost: 2,
    fervorValue: 0,
    description: 'Cache le score pendant 7 secondes.',
    effects: [{ type: 'hide_score', duration: 7 }],
    imageUrl: 'https://picsum.photos/seed/whistle/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_12',
    name: 'Hors-jeu',
    type: 'malus',
    rarity: 'epic',
    energyCost: 6,
    fervorValue: 0,
    description: 'Défausse une carte de la main adverse.',
    effects: [{ type: 'discard_enemy_cards' }],
    imageUrl: 'https://picsum.photos/seed/offside/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'double-ferveur',
    name: 'Double Ferveur',
    description: 'Vos clics comptent double pendant 5 secondes.',
    rarity: 'rare',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 8,
    effects: [{ type: 'double_points', duration: 5 }],
    imageUrl: 'https://picsum.photos/seed/double/400/600',
    fanzIds: []
  },
  {
    id: 'bouclier-divin',
    name: 'Bouclier Divin',
    description: 'Vous protège du prochain malus adverse.',
    rarity: 'epic',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 6,
    effects: [{ type: 'shield' }],
    imageUrl: 'https://picsum.photos/seed/shield/400/600',
    fanzIds: []
  },
  {
    id: 'seisme',
    name: 'Séisme',
    description: 'Fait trembler l\'écran de l\'adversaire.',
    rarity: 'rare',
    type: 'malus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'earthquake', duration: 3 }],
    imageUrl: 'https://picsum.photos/seed/quake/400/600',
    fanzIds: []
  },
  {
    id: 'miroir-magique',
    name: 'Miroir Magique',
    description: 'Renvoie le prochain malus à l\'adversaire.',
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 5,
    fervorValue: 10,
    effects: [{ type: 'mirror' }],
    imageUrl: 'https://picsum.photos/seed/mirror/400/600',
    fanzIds: []
  },
  {
    id: 'boutons-fantomes',
    name: 'Boutons Fantômes',
    description: 'Affiche de faux boutons sur l\'écran adverse.',
    rarity: 'epic',
    type: 'malus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'fake_buttons', duration: 5 }],
    imageUrl: 'https://picsum.photos/seed/ghost/400/600',
    fanzIds: []
  },
  {
    id: 'unlock_skill_1',
    name: 'Force Brute',
    type: 'bonus',
    rarity: 'rare',
    energyCost: 4,
    fervorValue: 15,
    description: 'Pousse la corde de 15%. Requis: Force Niv. 3',
    effects: [{ type: 'push_rope', value: 15 }],
    imageUrl: 'https://picsum.photos/seed/brute/200/300',
    unlockRequirements: [{ type: 'skill', skillName: 'force', minLevel: 3 }]
  },
  {
    id: 'unlock_ferveur_1',
    name: 'Aura de Ferveur',
    type: 'bonus',
    rarity: 'epic',
    energyCost: 5,
    fervorValue: 0,
    description: 'Double la régénération d\'excitation. Requis: Ferveur Niv. 2',
    effects: [{ type: 'energy_regen_boost', duration: 10 }],
    imageUrl: 'https://picsum.photos/seed/aura/200/300',
    unlockRequirements: [{ type: 'ferveur', minLevel: 2 }]
  },
  {
    id: 'unlock_rank_1',
    name: 'Légende du Fanz',
    type: 'bonus',
    rarity: 'legendary',
    energyCost: 8,
    fervorValue: 25,
    description: 'Pousse la corde de 25%. Requis: Rang Fanz 5',
    effects: [{ type: 'push_rope', value: 25 }],
    imageUrl: 'https://picsum.photos/seed/legend/200/300',
    unlockRequirements: [{ type: 'rank', minLevel: 5 }]
  },
  {
    id: 'mimic',
    name: 'Imitation',
    description: 'Copie le dernier malus joué par l\'adversaire.',
    rarity: 'legendary',
    type: 'neutral',
    energyCost: 6,
    fervorValue: 0,
    effects: [{ type: 'mimic' }],
    imageUrl: 'https://picsum.photos/seed/mimic/400/600',
    fanzIds: []
  },
  {
    id: 'lucky_draw',
    name: 'Main de la Chance',
    description: 'Remplace une carte de votre main par une carte aléatoire de rareté supérieure.',
    rarity: 'epic',
    type: 'bonus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'lucky_draw' }],
    imageUrl: 'https://picsum.photos/seed/luck/400/600',
    fanzIds: []
  },
  {
    id: 'swap_hands',
    name: 'Échange Standard',
    description: 'Échange votre main avec celle de l\'adversaire.',
    rarity: 'legendary',
    type: 'neutral',
    energyCost: 7,
    fervorValue: 0,
    effects: [{ type: 'swap_hands' }],
    imageUrl: 'https://picsum.photos/seed/swap/400/600',
    fanzIds: []
  },
  {
    id: 'fanz-001-poussette',
    name: "L'Aura de la Poussette",
    description: "Protection ultime : vous êtes immunisé contre le prochain malus joué par votre adversaire.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 0,
    effects: [{ type: 'shield' }],
    imageUrl: 'https://cdn.leonardo.ai/users/e39893af-e6c8-477d-bbbf-f9ed93c9d74e/image_generations/9264c8d1-d2c6-4d04-bbb7-5c5ebf899eab/Leonardo_Phoenix_10_A_close_up_of_a_baby_stroller_decked_out_i_3.jpg',
    fanzIds: ['fanz-001']
  },
  {
    id: 'fanz-001-regurgitation',
    name: "Régurgitation sur le Maillot",
    description: "Le bébé ruine son équipement. Déconcentre l'adversaire et lui supprime 3 points d'excitation instantanément.",
    rarity: 'rare',
    type: 'malus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'drain_energy', value: 3 }],
    imageUrl: 'https://cdn.leonardo.ai/users/e39893af-e6c8-477d-bbbf-f9ed93c9d74e/image_generations/ffcf0b74-325d-4f7f-ba00-2f1687f893e5/Leonardo_Phoenix_10_A_close_up_of_a_tastylooking_stain_on_a_ne_2.jpg',
    fanzIds: ['fanz-001']
  },
  {
    id: 'fanz-001-tetine',
    name: "La Tétine Tombe par Terre",
    description: "Le stade s'arrête face au drame ! Gèle les actions de l'adversaire pendant 5 secondes le temps de la retrouver.",
    rarity: 'epic',
    type: 'neutral',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'freeze_button', duration: 5 }],
    imageUrl: 'https://cdn.leonardo.ai/users/e39893af-e6c8-477d-bbbf-f9ed93c9d74e/image_generations/0e1b10e4-ff2e-4b47-bbf1-8dc17eb73e6a/Leonardo_Phoenix_10_A_pacifier_with_a_football_pattern_lying_2.jpg',
    fanzIds: ['fanz-001']
  },
  {
    id: 'base_steal_energy',
    name: "Vol d'Excitation",
    description: "Siphonne 2 points d'excitation à l'adversaire et vous les donne.",
    rarity: 'rare',
    type: 'bonus',
    energyCost: 2,
    fervorValue: 0,
    effects: [{ type: 'steal_energy', value: 2 }],
    imageUrl: 'https://picsum.photos/seed/steal/200/300',
    fanzIds: []
  },
  {
    id: 'base_cleanse',
    name: "Purge",
    description: "Annule instantanément tous vos malus actifs (bouton flou, caché...).",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'cleanse' }],
    imageUrl: 'https://picsum.photos/seed/cleanse/200/300',
    fanzIds: []
  },
  {
    id: 'base_vampirism',
    name: "Vampirisme",
    description: "Pendant 5 secondes, vos clics drainent légèrement la ferveur de l'adversaire.",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 6,
    fervorValue: 0,
    effects: [{ type: 'vampirism', duration: 5 }],
    imageUrl: 'https://picsum.photos/seed/vamp/200/300',
    fanzIds: []
  },
  {
    id: 'base_fog_of_war',
    name: "Cécité Tactique",
    description: "Masque l'interface de l'adversaire de façon chaotique pendant 6 secondes.",
    rarity: 'epic',
    type: 'malus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'fog_of_war', duration: 6 }],
    imageUrl: 'https://picsum.photos/seed/fog/200/300',
    fanzIds: []
  },
  {
    id: 'base_frenzy',
    name: "Frénésie",
    description: "Pendant 3 secondes, vos cartes ne coûtent plus aucune énergie !",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 9,
    fervorValue: 0,
    effects: [{ type: 'frenzy', duration: 3 }],
    imageUrl: 'https://picsum.photos/seed/frenzy/200/300',
    fanzIds: []
  },
  {
    id: 'base_sabotage',
    name: "Sabotage",
    description: "La FAUTE PROFESSIONNELLE ! La prochaine carte jouée par l'adversaire verra son coût doublé.",
    rarity: 'rare',
    type: 'malus',
    energyCost: 4,
    fervorValue: 0,
    effects: [{ type: 'sabotage' }],
    imageUrl: 'https://picsum.photos/seed/sabotage/200/300',
    fanzIds: []
  },
  {
    id: 'base_immunity',
    name: "Immunité Diplomatique",
    description: "Vous êtes insensible aux malus extérieurs pendant 8 secondes.",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 8,
    fervorValue: 0,
    effects: [{ type: 'immunity', duration: 8 }],
    imageUrl: 'https://picsum.photos/seed/immune/200/300',
    fanzIds: []
  },
  {
    id: 'base_critical_strike',
    name: "Frappe Critique",
    description: "Votre prochain clic comptera 5 fois plus !",
    rarity: 'rare',
    type: 'bonus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'critical_strike' }],
    imageUrl: 'https://picsum.photos/seed/crit/200/300',
    fanzIds: []
  },
  {
    id: 'base_momentum',
    name: "Momentum",
    description: "La foule est avec vous ! La ferveur augmente toute seule pendant 5 secondes.",
    rarity: 'epic',
    type: 'neutral',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'momentum', duration: 5 }],
    imageUrl: 'https://picsum.photos/seed/momentum/200/300',
    fanzIds: []
  },
  {
    id: 'base_overload',
    name: "Surcharge",
    description: "Faites le plein d'énergie (+10) instantanément, mais perdez 5% de ferveur au passage.",
    rarity: 'epic',
    type: 'neutral',
    energyCost: 0,
    fervorValue: -5,
    effects: [{ type: 'overload' }],
    imageUrl: 'https://picsum.photos/seed/overload/200/300',
    fanzIds: []
  },
  {
    id: 'base_invert_rope',
    name: "Retournement de Veste",
    description: "Panique totale ! La corde s'inverse. Si vous étiez mené, vous prenez l'avantage. (Reste centré si proche de 50%).",
    rarity: 'legendary',
    type: 'neutral',
    energyCost: 10,
    fervorValue: 0,
    effects: [{ type: 'invert_rope' }],
    imageUrl: 'https://picsum.photos/seed/invert/200/300',
    fanzIds: []
  },
  {
    id: 'base_blackout',
    name: "Coupure de Courant",
    description: "Plonge le stade adverse dans le noir complet pendant 8 secondes !",
    rarity: 'epic',
    type: 'malus',
    energyCost: 6,
    fervorValue: 0,
    effects: [{ type: 'blackout', duration: 8 }],
    imageUrl: 'https://picsum.photos/seed/blackout/200/300',
    fanzIds: []
  },
  {
    id: 'base_curse',
    name: "Malédiction Vaudou",
    description: "La prochaine carte de l'adversaire coûtera 3 énergies supplémentaires !",
    rarity: 'rare',
    type: 'malus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'curse' }],
    imageUrl: 'https://picsum.photos/seed/curse/200/300',
    fanzIds: []
  },
  {
    id: 'base_blessing',
    name: "Bénédiction du Kop",
    description: "Toutes vos cartes coûtent 2 d'énergie en moins pendant 10 secondes.",
    rarity: 'epic',
    type: 'bonus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'blessing', duration: 10 }],
    imageUrl: 'https://picsum.photos/seed/bless/200/300',
    fanzIds: []
  },
  {
    id: 'base_confetti',
    name: "Avalanche de Confettis",
    description: "Inonde l'écran de l'adversaire de confettis pendant 7 secondes, réduisant la visibilité.",
    rarity: 'common',
    type: 'malus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'confetti', duration: 7 }],
    imageUrl: 'https://picsum.photos/seed/confetti/200/300',
    fanzIds: []
  },
  {
    id: 'base_golden_goal',
    name: "Balle de Match",
    description: "Votre prochain clic a un impact dévastateur (x15) !!",
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 8,
    fervorValue: 0,
    effects: [{ type: 'golden_goal' }],
    imageUrl: 'https://picsum.photos/seed/goldengoal/200/300',
    fanzIds: []
  },
  {
    id: 'base_hypnosis',
    name: "Hypnose Collective",
    description: "Pendant 4 secondes, l'adversaire clique POUR votre équipe sans s'en rendre compte !",
    rarity: 'legendary',
    type: 'malus',
    energyCost: 10,
    fervorValue: 0,
    effects: [{ type: 'hypnosis', duration: 4 }],
    imageUrl: 'https://picsum.photos/seed/hypno/200/300',
    fanzIds: []
  }
];
