import type { Card } from '../types.ts';

export const BASE_CARDS: Card[] = [
  {
    id: 'base_1',
    name: 'Cri de Guerre',
    type: 'bonus',
    rarity: 'common',
    energyCost: 2,
    fervorValue: 5,
    description: 'Pousse la corde de 5% vers votre équipe.',
    effects: [{ type: 'push_rope', value: 5 }],
    imageUrl: 'https://picsum.photos/seed/war/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_2',
    name: 'Fumigène',
    type: 'malus',
    rarity: 'common',
    energyCost: 3,
    fervorValue: 0,
    description: 'Floute la vue de l\'adversaire pendant 5 secondes.',
    effects: [{ type: 'blur_view', duration: 5 }],
    imageUrl: 'https://picsum.photos/seed/smoke/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_3',
    name: 'Tifo Géant',
    type: 'bonus',
    rarity: 'rare',
    energyCost: 5,
    fervorValue: 12,
    description: 'Pousse la corde de 12% vers votre équipe.',
    effects: [{ type: 'push_rope', value: 12 }],
    imageUrl: 'https://picsum.photos/seed/tifo/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_4',
    name: 'Chant de Ralliement',
    type: 'bonus',
    rarity: 'common',
    energyCost: 3,
    fervorValue: 0,
    description: 'Rend 4 points d\'excitation.',
    effects: [{ type: 'refill_energy', value: 4 }],
    imageUrl: 'https://picsum.photos/seed/chant/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_5',
    name: 'Vuvuzela',
    type: 'malus',
    rarity: 'common',
    energyCost: 4,
    fervorValue: 0,
    description: 'Vole 3 points d\'excitation à l\'adversaire.',
    effects: [{ type: 'drain_energy', value: 3 }],
    imageUrl: 'https://picsum.photos/seed/noise/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_6',
    name: 'Blackout',
    type: 'malus',
    rarity: 'epic',
    energyCost: 6,
    fervorValue: 0,
    description: 'Fait disparaître le bouton de l\'adversaire pendant 4 secondes.',
    effects: [{ type: 'hide_button', duration: 4 }],
    imageUrl: 'https://picsum.photos/seed/dark/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_7',
    name: 'Mini-Ballon',
    type: 'malus',
    rarity: 'rare',
    energyCost: 4,
    fervorValue: 0,
    description: 'Réduit la taille du bouton adverse pendant 6 secondes.',
    effects: [{ type: 'shrink_button', duration: 6 }],
    imageUrl: 'https://picsum.photos/seed/small/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_8',
    name: 'Vent de Panique',
    type: 'malus',
    rarity: 'epic',
    energyCost: 5,
    fervorValue: 0,
    description: 'Le bouton adverse se déplace pendant 8 secondes.',
    effects: [{ type: 'move_button', duration: 8 }],
    imageUrl: 'https://picsum.photos/seed/wind/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_9',
    name: 'Carton Rouge',
    type: 'malus',
    rarity: 'epic',
    energyCost: 7,
    fervorValue: 0,
    description: 'Gèle le bouton adverse pendant 3 secondes.',
    effects: [{ type: 'freeze_button', duration: 3 }],
    imageUrl: 'https://picsum.photos/seed/redcard/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_10',
    name: 'Olé!',
    type: 'neutral',
    rarity: 'rare',
    energyCost: 4,
    fervorValue: 0,
    description: 'Mélange la main de l\'adversaire.',
    effects: [{ type: 'shuffle_deck' }],
    imageUrl: 'https://picsum.photos/seed/ole/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_11',
    name: 'Coup de Sifflet',
    type: 'malus',
    rarity: 'common',
    energyCost: 2,
    fervorValue: 0,
    description: 'Cache le score pendant 7 secondes.',
    effects: [{ type: 'hide_score', duration: 7 }],
    imageUrl: 'https://picsum.photos/seed/whistle/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'base_12',
    name: 'Hors-jeu',
    type: 'malus',
    rarity: 'epic',
    energyCost: 6,
    fervorValue: 0,
    description: 'Défausse une carte de la main adverse.',
    effects: [{ type: 'discard_enemy_cards' }],
    imageUrl: 'https://picsum.photos/seed/offside/200/300',
    videoUrl: '',
    fanzIds: []
  },
  {
    id: 'double-ferveur',
    name: 'Double Ferveur',
    description: 'Vos clics comptent double pendant 5 secondes.',
    rarity: 'rare',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 8,
    effects: [{ type: 'double_points', duration: 5 }],
    imageUrl: 'https://picsum.photos/seed/double/400/600',
    fanzIds: []
  },
  {
    id: 'bouclier-divin',
    name: 'Bouclier Divin',
    description: 'Vous protège du prochain malus adverse.',
    rarity: 'epic',
    type: 'bonus',
    energyCost: 4,
    fervorValue: 6,
    effects: [{ type: 'shield' }],
    imageUrl: 'https://picsum.photos/seed/shield/400/600',
    fanzIds: []
  },
  {
    id: 'seisme',
    name: 'Séisme',
    description: 'Fait trembler l\'écran de l\'adversaire.',
    rarity: 'rare',
    type: 'malus',
    energyCost: 3,
    fervorValue: 0,
    effects: [{ type: 'earthquake', duration: 3 }],
    imageUrl: 'https://picsum.photos/seed/quake/400/600',
    fanzIds: []
  },
  {
    id: 'miroir-magique',
    name: 'Miroir Magique',
    description: 'Renvoie le prochain malus à l\'adversaire.',
    rarity: 'legendary',
    type: 'bonus',
    energyCost: 5,
    fervorValue: 10,
    effects: [{ type: 'mirror' }],
    imageUrl: 'https://picsum.photos/seed/mirror/400/600',
    fanzIds: []
  },
  {
    id: 'boutons-fantomes',
    name: 'Boutons Fantômes',
    description: 'Affiche de faux boutons sur l\'écran adverse.',
    rarity: 'epic',
    type: 'malus',
    energyCost: 5,
    fervorValue: 0,
    effects: [{ type: 'fake_buttons', duration: 5 }],
    imageUrl: 'https://picsum.photos/seed/ghost/400/600',
    fanzIds: []
  },
  {
    id: 'unlock_skill_1',
    name: 'Force Brute',
    type: 'bonus',
    rarity: 'rare',
    energyCost: 4,
    fervorValue: 15,
    description: 'Pousse la corde de 15%. Requis: Force Niv. 3',
    effects: [{ type: 'push_rope', value: 15 }],
    imageUrl: 'https://picsum.photos/seed/brute/200/300',
    unlockRequirements: [{ type: 'skill', skillName: 'force', minLevel: 3 }]
  },
  {
    id: 'unlock_ferveur_1',
    name: 'Aura de Ferveur',
    type: 'bonus',
    rarity: 'epic',
    energyCost: 5,
    fervorValue: 0,
    description: 'Double la régénération d\'excitation. Requis: Ferveur Niv. 2',
    effects: [{ type: 'energy_regen_boost', duration: 10 }],
    imageUrl: 'https://picsum.photos/seed/aura/200/300',
    unlockRequirements: [{ type: 'ferveur', minLevel: 2 }]
  },
  {
    id: 'unlock_rank_1',
    name: 'Légende du Fanz',
    type: 'bonus',
    rarity: 'legendary',
    energyCost: 8,
    fervorValue: 25,
    description: 'Pousse la corde de 25%. Requis: Rang Fanz 5',
    effects: [{ type: 'push_rope', value: 25 }],
    imageUrl: 'https://picsum.photos/seed/legend/200/300',
    unlockRequirements: [{ type: 'rank', minLevel: 5 }]
  }
];
